server:
  port: 8082

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://localhost:3306/simpleecom_productdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: mySecretKey1234567890
  expirationMs: 86400000

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
