server:
  port: 8083

spring:
  application:
    name: cart-service

  datasource:
    url: jdbc:mysql://localhost:3306/simpleecom_cartdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: mySecretKey1234567890
  expirationMs: 86400000

spring.main.allow-bean-definition-overriding: true
